### user sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

    {
        "name":"Myfirstone",
        "company":"Myfirstone",
        "address":"Myfirstone",
        "phone":"23455432",
        "email":"Mystonee@e.com",
        "password":"Secret123"
    }
### user sign in endpoint

POST http://localhost:3001/v1/user/login
Content-Type: application/json

    {
        "email":"Mystonee@e.com",
        "password":"Secret123"
    }

### user sign in endpoint


GET http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik15c3RvbmVlQGUuY29tIiwiaWF0IjoxNzAzMzM0NzA3LCJleHAiOjE3MDMzMzQ3Njd9.XHcGaNhCdFTWuGwCgKk82TjT-TEaPWwuid3x_QQxMDU



#####tokens router
###get refreshed token
GET http://localhost:3001/v1/token
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik15c3RvbmVlQGUuY29tIiwiaWF0IjoxNzAzMTU3NjE5LCJleHAiOjE3MDU3NDk2MTl9.5H4hZ7pYncIiWE7V6Jf15OKw3PtfoCt_Vd5Gn10ZyCE

### reset password user

POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

    {
        "email":"Mystonee@e.com"
    }

